### ISSUE TITLE
Threads vs Bruteforce TSP question

### ISSUE THREAD

**Issue by Bogdaan** [graphp/algorithms#17]
Bruteforce find best solution, but it too slow. 

Its posible use php threads in Bruteforce TSP algo implementation ?

**Comment by clue** [comment]
> but it's too slow

"TSP  is  known  as  an  NP-hard  program  that  causes  a  computational  explosion" ¹, you read up more on this on http://en.wikipedia.org/wiki/Travelling_salesman_problem. I'm curious if you happen to come up with a solution that is not *slow* ;-)

> is it posible use php threads…?

Absolutely! It's certainly *possible* to use threads and I'd be curious to see how significant the speedup would be. The bruteforce algorithms simply tries all possible combinations, so one possible approach would be to split up the number of combinations evenly among all available CPU cores¹.

PRs would be much appreciated! :+1: I hope this answers your question! :)

¹: http://courses.washington.edu/css534/prog/prog1.pdf
