### ISSUE TITLE
Confusing method DepthFirst::getVertices() - could add explanatory comments

### ISSUE THREAD

**Issue by phyrwork** [graphp/algorithms#24]
`DepthFirst::getVertices()` demonstrates how both the iterative and recursive versions of the algorithm should be used - but clearly the second example is not reachable and the primary methods are themselves private.

My guess is that the iterative version should always be used and hence is the one that will be called from `getVertices()`, since with any sizeable graphs the call depth limit will be reached.

Ideally comments should be added to explain what's going on with the weird double return value example thing.

**Comment by clue** [comment]
Thanks for spotting and I agree that we should remove the dead code here :+1: 

The iterative version would indeed be preferable over the recursive one. However given that the recursive one is currently in use, I would probably accept either one.

Do you feel like filing a PR? :shipit:
