### ISSUE TITLE
Support topological sorting on Disconnected Graphs

### ISSUE THREAD

**Issue by Incognito** [graphp/algorithms#42]
When using a disconnected graph the topological sort will not fully sort all nodes.

There is a work-around: use `(new ConnectedComponents($graph))->createGraphsComponents()` and sort each graph individually. The draw-back here is that finding all connected components is a very time-expensive task (for example, it takes roughly 2-3 minutes when I get 2000~ components form a 6000~ vertex graph).

**Comment by Incognito** [comment]
I can no longer reproduce, I think I misinterpreted results because I directly put the sorted graph into graphviz.

**Comment by clue** [comment]
@Incognito Thanks for reporting back, happy to hear this is resolved either way! :+1:
