### ISSUE TITLE
Is there a Transitive Reduction algorithm available?

### ISSUE THREAD

**Issue by xi-ao** [graphp/algorithms#49]
Hi,

I'm looking for a way to reduce a dependency graph in order to remove redundant links in it.
I came to the conclusion that [Transitive Reduction](https://en.wikipedia.org/wiki/Transitive_reduction) seems to be the right way to do it, but I cannot find it in the available algorithms in this repo.

Can you confirm it does not exist? (and as a consequence, that if I need it I have to code it, obviously ^^)

Thanks

**Comment by SimonFrings** [comment]
Hey @xi-ao, thanks for bringing this up :+1:

I can confirm that this does not exist in this project yet ^^

If you happen to have some kind of implementation for this we're more than happy about PRs. 🔥

**Comment by xi-ao** [comment]
Thanks! I'll try to find the time to implement it, that sounds fun to do :smile:
